# Generated by Django 3.0.5 on 2020-10-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_title_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
